language: php

php:
    - 5.6

os:
    - linux

sudo: true

dist: trusty

cache:
  timeout: 500
  directories:
  - vendor
  
git:
  depth: false
  submodules: false

install:
  - composer update

script:
  - echo "No script to run"

branches:
  only:
    master

notifications:
    email:
      on_success: always
      on_failure: always
